language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email:
    - sunbergzach@gmail.com
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("POMDPModels"); Pkg.test("POMDPModels"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("POMDPModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
