language: julia
os:
  - linux
julia:
  - release
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("POMDPModels"); Pkg.add("NBInclude"); Pkg.test("POMDPModels"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("POMDPModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

